services:
  py_check_cert:
    container_name: py_check_cert
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - "py_check_cert"
    env_file: ".env"
    command: celery -A main worker --beat --loglevel=info
    depends_on:
      - redis
  redis:
    container_name: cert_check_redis
    image: redis:latest
    ports:
      - 6379:6379